name: Pylint

on:
  workflow_dispatch:
  push:
    paths: 
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pylint
        sudo apt-get install -y python3-numpy python3-matplotlib
        python3 -m pip install tf-keras
        python3 -m pip install click
        python3 -m pip install gym
        python3 -m pip install PyFina
        python3 -m pip install keras
        python3 -m pip install --upgrade tensorflow
        pip3 list
        python3 howto/using_tfdotkeras_add_layer.py
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
